---
#-------------------------------
# General Site Settings

title: PSF
logo:
author: Armin Hadziosmanovic
description: LE PORALIMPIADI - 10° Anniversario - 7 Febbraio 2026 - Limited Edition
email: begaraj@gmail.com
phone: 
address: Clusone
copyright: Copyright &copy; 2026 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: LE PORALIMPIADI <br> 10° Anniversario <br> 7 Febbraio 2026

social:
  - { icon: "ti-instagram", link: "https://www.instagram.com/porasenzafrontiere/" }
  - { icon: "ti-facebook", link: "https://www.facebook.com/PoraSF" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Dopo 9 edizioni indimenticabili, PORA Senza Frontiere celebra il suo 10° anniversario con LE PORALIMPIADI - un evento unico ispirato alle Olimpiadi invernali. Limited Edition con solo 50 partecipanti, 25 squadre da 2 persone, spirito olimpico e ironia garantita. Un evento irripetibile che farà storia.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Web Design, color: "#fdb157", value: "90%" }
  - { name: Logo Design, color: "#9473e6", value: "60%" }
  - { name: After Effects, color: "#bdecf6", value: "80%" }
  - { name: Web App, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Junior UX Designer,
      icon: "icon-1.png",
      date: "Jan 2007 - Feb 2009",
      organization: "WEBEX",
    }
  - {
      name: UX & UI Designer,
      icon: "icon-2.png",
      date: "Mar 2009 - Aug 2014",
      organization: "AUGMEDIX",
    }
  - {
      name: Senior UI Designer,
      icon: "icon-3.png",
      date: "Sep 2014 - Present",
      organization: "THEMEFISHER",
    }

#-------------------------------
# Education Section

education-title: I Giochi Olimpici
education:
  - {
      name: Cerimonia di Apertura,
      date: "7 Febbraio 2026",
      organization: "Passaggio della Fiaccola Olimpica",
    }
  - {
      name: Giochi a Squadre,
      date: "7 Febbraio 2026",
      organization: "25 Nazioni in Competizione",
    }
  - {
      name: Cerimonia di Chiusura,
      date: "7 Febbraio 2026",
      organization: "Premiazione Medaglie e Festa con DJ Lorisio",
    }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Italia ,
      icon: it,
      description: "Descrizione",
      active: True,# Add true to select section
    }
  - {
        name: Jamaica ,
        icon: jm,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Giappone ,
        icon: jp,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Argentina ,
        icon: ar,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Svizzera,
        icon: ch,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Germania ,
        icon: de,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Città del Vaticano ,
        icon: va,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Cuba ,
        icon: cu,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Brasile ,
        icon: br,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Australia ,
        icon: au,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Irlanda ,
        icon: ie,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Spagna ,
        icon: es,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Usa ,
        icon: us,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: India ,
        icon: in,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Perù ,
        icon: pe,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Scozia ,
        icon: gb-sct,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Francia ,
        icon: fr,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Messico ,
        icon: mx,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Egitto ,
        icon: eg,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Hawaii ,
        icon: us-hi,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Groenlandia ,
        icon: gl,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Olanda ,
        icon: nl,
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Norvegia ,
        icon: 'no',
        description: "Descrizione",
        active: True,# Add true to select section
      }
  - {
        name: Arabia,
        icon: ae,
        description: "Descrizione",
        active: True,# Add true to select section
      }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Cerimonia di Apertura"
    image: "assets/images/testimonial/client-1.png"
    designation: "Ingresso Atleti"
    content: "Passaggio della fiaccola olimpica tra le 25 nazioni partecipanti. Presentazione ufficiale delle squadre e giuramento olimpico. <strong>L'inizio di una leggenda.</strong>"

  - name: "Le Gare Olimpiche"
    image: "assets/images/testimonial/client-1.png"
    designation: "Sfide a Squadre"
    content: "Sfide a squadre da 2 persone in veri giochi olimpici invernali rivisitati in chiave PORA. <strong>Solo i migliori conquisteranno il podio.</strong>"

  - name: "Cerimonia di Chiusura"
    image: "assets/images/testimonial/client-1.png"
    designation: "Premiazioni e Festa"
    content: "Premiazione delle squadre vincitrici con medaglie d'oro, argento e bronzo. <strong>Festa con DJ Lorisio. Eddie the Eagle sarà orgoglioso di voi.</strong>"

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/logo_mlengraving.png"
    url: "https://www.mlengraving.com/"

  - logo: "assets/images/clients-logo/ortovoxlogo.png"
    url: "https://www.ortovox.com/"

  - logo: "assets/images/clients-logo/logo_mlengraving.png"
    url: "https://www.mlengraving.com/"

  - logo: "assets/images/clients-logo/ortovoxlogo.png"
    url: "https://www.ortovox.com/"

  - logo: "assets/images/clients-logo/logo_mlengraving.png"
    url: "https://www.mlengraving.com/"

  - logo: "assets/images/clients-logo/ortovoxlogo.png"
    url: "https://www.ortovox.com/"

  - logo: "assets/images/clients-logo/logo_mlengraving.png"
    url: "https://www.mlengraving.com/"

  - logo: "assets/images/clients-logo/ortovoxlogo.png"
    url: "https://www.ortovox.com/"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
